Added support for building docker image
companieshouse/onboarding-portal-webapp pull request #4
Opened 2021-03-22 16:21 UTC by ICoxCH

2021-03-22 16:21 UTC, ICoxCH commented on .dockerignore
> +node_modules
Do not copy anything covered by this file into the docker image.

2021-03-22 16:22 UTC, ICoxCH commented on Dockerfile
> +FROM node:14
Start with a minimised linux distribution with Node 14 installed

2021-03-22 16:23 UTC, ICoxCH commented on Dockerfile
> +COPY package*.json ./
Move both package.json and package-lock.json into the image

2021-03-22 16:23 UTC, ICoxCH commented on Dockerfile
> +RUN npm install
download dependencies for application

2021-03-22 16:24 UTC, ICoxCH commented on Dockerfile
> +COPY . .
copy everything not covered by .dockerignore into the image

2021-03-22 16:24 UTC, ICoxCH commented on Dockerfile
> +EXPOSE 3000
open port 3000 on image this lines up with port that the application listens on. Allowing the app to be hit by the outside world

2021-03-22 16:25 UTC, ICoxCH commented on Dockerfile
> +CMD [ "node", "./bin/www" ]
when the image is spun up, the command that is ran `node ./bin/www`

2021-03-23 13:42 UTC, amyatt1CH requested changes
All looks fine - only thing I'd mention is updating the README to show usage with docker. e.g.
`run docker build -t onboarding-portal-webapp .` then run `docker run -t -i -p 3000:3000 onboarding-portal-webapp` (they don't have to be these exact commands or arguments, just an example)

2021-03-23 14:18 UTC, amyatt1CH approved these changes
👍

2021-03-23 15:34 UTC, merged