Adding mock API feature flag to service
companieshouse/onboarding-portal-webapp pull request #8
Opened 2021-03-25 17:43 UTC by gevans-ch

2021-03-26 07:51 UTC, ICoxCH approved these changes

2021-03-26 07:53 UTC, ICoxCH commented on services/contentService.js
> +    console.log(process.env.MOCK_API_RESPONSES)
this log is probably not actually needed

2021-03-26 08:12 UTC, ICoxCH requested changes

2021-03-26 08:12 UTC, ICoxCH commented on services/contentService.js
> +    if (process.env.MOCK_API_RESPONSES !== true) {
we should update the readme aswell, mentioning this variable, and the json file and what they do

2021-04-08 14:05 UTC, ICoxCH approved these changes

2021-04-08 14:18 UTC, amyatt1CH approved these changes
Happy to approve, changes requested are done and bug is fixed.

2021-04-08 14:18 UTC, merged